### ISSUE TITLE
Add Copy to Clipboard feature

### ISSUE THREAD

**Issue by KshitijDarekar** [KshitijDarekar/Codeditor#1]
Add buttons(icons) to copy the code snippets from the HTML, CSS, and JS coding window to the clipboard.

Deliverables:

- [ ] Add icons(button) to copy text to clipboard
- [ ] Implement the functionality to copy the text from the particular coding window

**Comment by avisharma344** [comment]
@KshitijDarekar  Can I work on this issue? Thanks!

**Comment by KshitijDarekar** [comment]
Hi @avisharma344, First of all, thank you so much for taking out the time to work on this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

**Comment by KshitijDarekar** [comment]
Hey, @avisharma344 it's been a few days, have you started working on this issue? @Aniket-508 has already made a PR #8 for the same issue, if you don't mind then we close this issue.

**Comment by avisharma344** [comment]
Sure ...You can close the issue🙂
