### ISSUE TITLE
Add themes to editor

### ISSUE THREAD

**Issue by KshitijDarekar** [KshitijDarekar/Codeditor#2]
The current editor uses only one default theme `material`.Add a dropdown menu, for the users to select multiple theme options.

**Comment by JoalbertMilano** [comment]
can i help you with this issue? i already made a pull requerst, take a look it

**Comment by KshitijDarekar** [comment]
@JoalbertMilano I have assigned the issue to you. Have reviewed your PR and suggested the changes.
Let me say you have done a great work 🙌
Hey, why don't you try registering in OpenCode? The registration is completely free and there are a lot of stuff like certificates and goodies in the room for participants..!
You can register through the registration form at the official website:
https://csirait.in/opencode/

**Comment by KshitijDarekar** [comment]
Great work @JoalbertMilano 
I really appreciate the way you resolved this issue. 💫
Really a wonderful quality PR's 🙌
Keep up the great work.

Looking forward for more contributions from your side 🔥 🙌

Also do checkout  OpenCode'22:
https://csirait.in/opencode/
to be considered to be on the leaderboard
