### ISSUE TITLE
Design a Landing Page

### ISSUE THREAD

**Issue by KshitijDarekar** [KshitijDarekar/Codeditor#3]
Design and code a landing page for the project. The landing page should have a link to the code editor.

**Comment by Aniket-508** [comment]
@KshitijDarekar I want to work on this issue.

**Comment by KshitijDarekar** [comment]
Hi @Aniket-508 , First of all, thank you so much for taking out the time to work on this issue.

Definitely 🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍

📌Just to add a few things :
We can discuss the possible design ideas over the discord channel of OpenCode'22.
This project is a part of OpenCode'22. The registration is completely free and there are a lot of stuff like certificates and goodies in the room for participants..! 
You can register through the registration form at the official website:
https://csirait.in/opencode/

**Comment by KshitijDarekar** [comment]
Great work @Aniket-508 
I really appreciate the way you resolved this issue. 💫
Really a wonderful quality PR's 🙌
Keep up the great work.

Looking forward to more contributions from your side 🔥 🙌
