### ISSUE TITLE
Add react-router-dom

### ISSUE THREAD

**Issue by KshitijDarekar** [KshitijDarekar/Codeditor#5]
Currently, there are no routes used in the project. Add react-router-dom for different routes like home, code-editor, etc.

**Comment by andrewkykoo** [comment]
@KshitijDarekar Can I work on this issue? Thanks!

**Comment by KshitijDarekar** [comment]
Definitely🙌, Please go forward to work on this issue. I am assigning this Issue to you 👍
Also refer the [CONTRIBUTING Guideline](https://github.com/KshitijDarekar/Codeditor/blob/master/CONTRIBUTING.md)

Keep Contributing 🙏🔥

**Comment by KshitijDarekar** [comment]
Hey, @andrewkykoo I hope you have started working on the issue, also why don't you try registering in OpenCode and then start contributing to this issue? The registration is completely free and there are lot of stuff like certificates and goodies in the room for participants..!
You can register through the registration form at the official website:
https://csirait.in/opencode/

**Comment by andrewkykoo** [comment]
@KshitijDarekar Yes. Working on this now and thanks for the link!

**Comment by andrewkykoo** [comment]
@KshitijDarekar What pages are you envisioning? I was thinking the most essential pages handled by the router - 1. Home 2. Editor 3. Contact. Also, how would you like the home page to look? (straight to editor like now, or landing page etc)? Thanks.

**Comment by KshitijDarekar** [comment]
> @KshitijDarekar What pages are you envisioning? I was thinking the most essential pages handled by the router - 1. Home 2. Editor 3. Contact. Also, how would you like the home page to look? (straight to editor like now, or landing page etc)? Thanks. 

Yes, as of now I have thought to keep the routes for 
1.Home
2.Editor
you can add extra routes if u want to,  we can keep them for future use.
In the home , route it should  be a landing page , there is already an issue open for that.From the landing page , the user would be directed to the editor .

**Comment by andrewkykoo** [comment]
@KshitijDarekar Okay. I am debating if it makes more sense for the person in charge of the landing page to add routes - if I knew there was an ongoing issue for the landing page, I would have taken care of both landing page and routes.. Let me know your thoughts! 

I am still willing to add a route to home on the editor, but prefer to have a landing page ready before I add routes. Let me know your thoughts!

**Comment by KshitijDarekar** [comment]
> @KshitijDarekar Okay. I am debating if it makes more sense for the person in charge of the landing page to add routes - if I knew there was an ongoing issue for the landing page, I would have taken care of both landing page and routes.. Let me know your thoughts!
> 
> I am still willing to add a route to home on the editor, but prefer to have a landing page ready before I add routes. Let me know your thoughts!

@andrewkykoo You are right, it does make sense. I had kept it as a separate issue so that even the beginners would find it easy to contribute. There is already a PR [#8 ](https://github.com/KshitijDarekar/Codeditor/pull/8) the landing page issue now, and the routes are implemented over there. So, if you haven't already started working on the issue, then we can close this issue.
